### ISSUE TITLE
Server TPS drops when opening the Player menu

### ISSUE THREAD

**Issue by TyrellPlayz** [TyrellPlayz/ServerMail#3]
The servers TPS drops when opening the Player menu to send a mail

**Comment by Legoman99573** [comment]
I believe the only fix is loading it on server start and add people in on join if they aren't added in. Idk why wait until someone runs the command imo, but it's up to you ;)

**Comment by TyrellPlayz** [comment]
That's a great idea thanks :)

**Comment by Legoman99573** [comment]
@TyrellPlayz good as for people with a large amount of joined players, it is possible to lock the main thread, which can crash the server.
